version: '3.9'

services:
  podopals:
    container_name: podopals_service
    image: ozkanbuyuk/podopals:1.0.0
    ports:
      - 5000:5000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=12345678
      - PG_DB=nestjs_podopals_case_db
      - PG_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=nestjs_podopals_case_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  pgdata: {}
